In [1]:
import sys
from pathlib import Path

ROOT = Path().resolve().parents[0]  # если скрипт, а не ноутбук
# в ноутбуке можно так:
# ROOT = Path().resolve()

sys.path.append(str(ROOT / "src"))

In [2]:
# Координаты Новороссийска
LATITUDE = 44.72439
LONGITUDE = 37.76752

# Период данных (ERA5-Land доступна с 1950, обновляется с задержкой 5 дней)
START_DATE = "2026-02-15"
# END_DATE = "2026-02-01"

In [3]:
from whether import Whether

whether = Whether(longitude=LONGITUDE, latitude=LATITUDE)

In [4]:
whether.download_whether_data(start_date="2025-12-15", end_date="2026-01-01", timeout=5)
# whether.download_whether_data(start_date="2026-01-15", timeout=5)
whether.whether_data

,date,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,snowfall_sum,precipitation_hours,wind_speed_10m_max,...,sunrise,sunset,sunshine_duration,daylight_duration,shortwave_radiation_sum,et0_fao_evapotranspiration,weather_code,year,month,day_of_year
0,2025-12-15,8.6,3.3,5.5,-0.8,4.5,4.2,0.21,13.0,18.4,...,2025-12-15T07:59,2025-12-15T16:49,9002.77,31777.72,2.36,0.54,71,2025,12,349
1,2025-12-16,3.1,0.7,-1.2,-3.8,0.2,0.2,0.00,2.0,20.9,...,2025-12-16T08:00,2025-12-16T16:49,25807.07,31751.56,5.42,0.55,51,2025,12,350
2,2025-12-17,10.2,0.4,8.9,-2.9,0.0,0.0,0.00,0.0,8.3,...,2025-12-17T08:00,2025-12-17T16:49,26354.56,31729.98,5.32,0.60,3,2025,12,351
3,2025-12-18,10.3,5.0,7.8,2.7,0.0,0.0,0.00,0.0,12.5,...,2025-12-18T08:01,2025-12-18T16:50,17652.51,31713.01,4.14,0.65,3,2025,12,352
4,2025-12-19,12.0,6.4,10.8,4.6,0.0,0.0,0.00,0.0,12.2,...,2025-12-19T08:02,2025-12-19T16:50,25449.22,31700.65,5.16,0.79,3,2025,12,353
5,2025-12-20,10.2,4.4,8.3,2.1,0.0,0.0,0.00,0.0,8.7,...,2025-12-20T08:02,2025-12-20T16:50,25767.64,31692.90,5.20,0.59,2,2025,12,354
6,2025-12-21,9.6,3.7,7.9,1.2,0.0,0.0,0.00,0.0,9.6,...,2025-12-21T08:03,2025-12-21T16:51,21945.73,31689.77,4.75,0.52,3,2025,12,355
7,2025-12-22,7.6,3.3,4.6,0.2,0.0,0.0,0.00,0.0,11.3,...,2025-12-22T08:03,2025-12-22T16:51,25158.86,31691.23,5.15,0.53,3,2025,12,356
8,2025-12-23,6.3,3.4,2.4,-1.2,0.0,0.0,0.00,0.0,17.5,...,2025-12-23T08:04,2025-12-23T16:52,22802.57,31697.30,4.49,0.63,3,2025,12,357
9,2025-12-24,4.9,1.0,-0.4,-4.3,0.0,0.0,0.00,0.0,20.6,...,2025-12-24T08:04,2025-12-24T16:53,26290.80,31707.97,6.26,0.97,2,2025,12,358
10,2025-12-25,0.5,-4.6,-5.0,-11.8,0.0,0.0,0.00,0.0,28.8,...,2025-12-25T08:04,2025-12-25T16:53,26992.69,31723.22,6.93,0.94,2,2025,12,359
11,2025-12-26,5.5,-3.8,0.1,-9.4,1.4,0.5,0.63,5.0,25.7,...,2025-12-26T08:05,2025-12-26T16:54,18646.33,31743.05,4.77,0.92,73,2025,12,360
12,2025-12-27,3.6,0.3,-0.5,-4.0,3.4,1.5,1.33,15.0,16.4,...,2025-12-27T08:05,2025-12-27T16:55,25348.76,31767.43,5.39,0.53,73,2025,12,361
13,2025-12-28,5.8,-0.8,0.7,-4.4,8.5,8.2,0.21,15.0,35.8,...,2025-12-28T08:05,2025-12-28T16:55,0.00,31796.35,1.74,0.44,71,2025,12,362
14,2025-12-29,3.6,0.9,-1.3,-5.0,3.2,2.9,0.21,17.0,24.9,...,2025-12-29T08:06,2025-12-29T16:56,17739.75,31829.79,4.23,0.63,71,2025,12,363
15,2025-12-30,7.5,1.0,3.1,-5.0,4.9,4.6,0.21,17.0,28.4,...,2025-12-30T08:06,2025-12-30T16:57,11703.08,31867.72,3.34,0.79,71,2025,12,364
16,2025-12-31,3.1,0.6,-0.7,-4.0,3.0,0.9,1.47,17.0,16.8,...,2025-12-31T08:06,2025-12-31T16:58,17243.53,31910.13,4.45,0.65,73,2025,12,365
17,2026-01-01,1.8,-1.9,-3.1,-6.3,0.0,0.0,0.00,0.0,17.6,...,2026-01-01T08:06,2026-01-01T16:59,23923.99,31956.97,5.56,0.85,3,2026,1,1

In [5]:
# whether.export_whether_data(file_path="whether.json")
# whether.export_whether_data(file_path="whether.csv")
# whether.export_whether_data(file_path="whether.xlsx")

In [6]:
whether_2 = Whether(longitude=LONGITUDE, latitude=LATITUDE)
whether_2.read_whether_data("whether.json")
whether_2.read_whether_data("whether.csv")
whether_2.read_whether_data("whether.xlsx")
whether_2.whether_data

,date,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,snowfall_sum,precipitation_hours,wind_speed_10m_max,...,sunrise,sunset,sunshine_duration,daylight_duration,shortwave_radiation_sum,et0_fao_evapotranspiration,weather_code,year,month,day_of_year
0,2026-01-15,4.6,0.4,0.8,-4.8,13.7,4.8,6.23,16.0,20.9,...,2026-01-15T08:02,2026-01-15T17:14,29.05,33088.98,3.03,0.50,75.0,2026,1,15
1,2026-01-16,-0.3,-3.2,-4.4,-8.1,3.2,0.0,2.24,6.0,21.4,...,2026-01-16T08:02,2026-01-16T17:15,27756.13,33198.27,7.02,0.63,75.0,2026,1,16
2,2026-01-17,-3.6,-7.9,-8.9,-14.8,2.6,0.0,1.82,12.0,28.8,...,2026-01-17T08:01,2026-01-17T17:16,13402.40,33310.48,5.92,0.34,73.0,2026,1,17
3,2026-01-18,-3.0,-6.0,-10.2,-13.1,0.0,0.0,0.00,0.0,32.5,...,2026-01-18T08:01,2026-01-18T17:18,26365.04,33425.46,7.34,0.43,3.0,2026,1,18
4,2026-01-19,-4.3,-7.5,-11.9,-15.6,0.0,0.0,0.00,0.0,37.6,...,2026-01-19T08:00,2026-01-19T17:19,27739.41,33543.05,7.77,0.38,3.0,2026,1,19
5,2026-01-20,-2.6,-9.9,-7.2,-16.4,0.0,0.0,0.00,0.0,27.5,...,2026-01-20T07:59,2026-01-20T17:20,28422.13,33663.09,8.73,0.49,3.0,2026,1,20
6,2026-02-15,12.5,7.9,6.9,4.8,0.0,0.0,0.00,0.0,39.0,...,2026-02-15T07:29,2026-02-15T17:56,20644.93,37637.72,7.46,1.23,3.0,2026,2,46
7,2026-02-16,13.4,9.2,9.4,6.0,1.8,1.8,0.00,3.0,42.1,...,2026-02-16T07:28,2026-02-16T17:58,29048.19,37813.00,7.24,1.83,61.0,2026,2,47
8,2026-02-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,...,2026-02-17T07:26,2026-02-17T17:59,NaN,37989.80,NaN,NaN,NaN,2026,2,48

In [7]:
whether.whether_data

,date,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,snowfall_sum,precipitation_hours,wind_speed_10m_max,...,sunrise,sunset,sunshine_duration,daylight_duration,shortwave_radiation_sum,et0_fao_evapotranspiration,weather_code,year,month,day_of_year
0,2025-12-15,8.6,3.3,5.5,-0.8,4.5,4.2,0.21,13.0,18.4,...,2025-12-15T07:59,2025-12-15T16:49,9002.77,31777.72,2.36,0.54,71,2025,12,349
1,2025-12-16,3.1,0.7,-1.2,-3.8,0.2,0.2,0.00,2.0,20.9,...,2025-12-16T08:00,2025-12-16T16:49,25807.07,31751.56,5.42,0.55,51,2025,12,350
2,2025-12-17,10.2,0.4,8.9,-2.9,0.0,0.0,0.00,0.0,8.3,...,2025-12-17T08:00,2025-12-17T16:49,26354.56,31729.98,5.32,0.60,3,2025,12,351
3,2025-12-18,10.3,5.0,7.8,2.7,0.0,0.0,0.00,0.0,12.5,...,2025-12-18T08:01,2025-12-18T16:50,17652.51,31713.01,4.14,0.65,3,2025,12,352
4,2025-12-19,12.0,6.4,10.8,4.6,0.0,0.0,0.00,0.0,12.2,...,2025-12-19T08:02,2025-12-19T16:50,25449.22,31700.65,5.16,0.79,3,2025,12,353
5,2025-12-20,10.2,4.4,8.3,2.1,0.0,0.0,0.00,0.0,8.7,...,2025-12-20T08:02,2025-12-20T16:50,25767.64,31692.90,5.20,0.59,2,2025,12,354
6,2025-12-21,9.6,3.7,7.9,1.2,0.0,0.0,0.00,0.0,9.6,...,2025-12-21T08:03,2025-12-21T16:51,21945.73,31689.77,4.75,0.52,3,2025,12,355
7,2025-12-22,7.6,3.3,4.6,0.2,0.0,0.0,0.00,0.0,11.3,...,2025-12-22T08:03,2025-12-22T16:51,25158.86,31691.23,5.15,0.53,3,2025,12,356
8,2025-12-23,6.3,3.4,2.4,-1.2,0.0,0.0,0.00,0.0,17.5,...,2025-12-23T08:04,2025-12-23T16:52,22802.57,31697.30,4.49,0.63,3,2025,12,357
9,2025-12-24,4.9,1.0,-0.4,-4.3,0.0,0.0,0.00,0.0,20.6,...,2025-12-24T08:04,2025-12-24T16:53,26290.80,31707.97,6.26,0.97,2,2025,12,358
10,2025-12-25,0.5,-4.6,-5.0,-11.8,0.0,0.0,0.00,0.0,28.8,...,2025-12-25T08:04,2025-12-25T16:53,26992.69,31723.22,6.93,0.94,2,2025,12,359
11,2025-12-26,5.5,-3.8,0.1,-9.4,1.4,0.5,0.63,5.0,25.7,...,2025-12-26T08:05,2025-12-26T16:54,18646.33,31743.05,4.77,0.92,73,2025,12,360
12,2025-12-27,3.6,0.3,-0.5,-4.0,3.4,1.5,1.33,15.0,16.4,...,2025-12-27T08:05,2025-12-27T16:55,25348.76,31767.43,5.39,0.53,73,2025,12,361
13,2025-12-28,5.8,-0.8,0.7,-4.4,8.5,8.2,0.21,15.0,35.8,...,2025-12-28T08:05,2025-12-28T16:55,0.00,31796.35,1.74,0.44,71,2025,12,362
14,2025-12-29,3.6,0.9,-1.3,-5.0,3.2,2.9,0.21,17.0,24.9,...,2025-12-29T08:06,2025-12-29T16:56,17739.75,31829.79,4.23,0.63,71,2025,12,363
15,2025-12-30,7.5,1.0,3.1,-5.0,4.9,4.6,0.21,17.0,28.4,...,2025-12-30T08:06,2025-12-30T16:57,11703.08,31867.72,3.34,0.79,71,2025,12,364
16,2025-12-31,3.1,0.6,-0.7,-4.0,3.0,0.9,1.47,17.0,16.8,...,2025-12-31T08:06,2025-12-31T16:58,17243.53,31910.13,4.45,0.65,73,2025,12,365
17,2026-01-01,1.8,-1.9,-3.1,-6.3,0.0,0.0,0.00,0.0,17.6,...,2026-01-01T08:06,2026-01-01T16:59,23923.99,31956.97,5.56,0.85,3,2026,1,1

In [9]:
whether.get_statistic_df()

,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,snowfall_sum,precipitation_hours,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant,sunshine_duration,daylight_duration,shortwave_radiation_sum,et0_fao_evapotranspiration,weather_code,year,month,day_of_year
count,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,27.000000,26.000000,26.000000,26.000000,26.000000,27.000000,26.000000,26.000000,26.000000,27.000000,27.000000,27.000000
mean,5.034615,0.242308,0.861538,-4.388462,1.938462,1.138462,0.560000,5.222222,22.469231,41.853846,144.384615,20816.813077,32793.207407,5.352692,0.690385,33.730769,2025.370370,8.037037,233.925926
std,5.137154,4.836128,6.347540,6.312991,3.222059,2.101252,1.318975,6.885511,9.699393,18.523763,116.928038,8139.855312,1932.476038,1.699559,0.310464,34.398323,0.492103,5.273165,163.853811
min,-4.300000,-9.900000,-11.900000,-16.400000,0.000000,0.000000,0.000000,0.000000,8.300000,15.100000,2.000000,0.000000,31689.770000,1.740000,0.340000,2.000000,2025.000000,1.000000,1.000000
25%,2.125000,-2.875000,-2.650000,-7.650000,0.000000,0.000000,0.000000,0.000000,16.500000,28.500000,36.250000,17674.320000,31718.115000,4.460000,0.522500,3.000000,2025.000000,1.500000,33.000000
50%,5.200000,0.650000,0.400000,-4.150000,0.000000,0.000000,0.000000,0.000000,20.900000,38.350000,116.000000,24541.425000,31796.350000,5.260000,0.615000,3.000000,2025.000000,12.000000,352.000000
75%,9.350000,3.375000,6.550000,-0.050000,3.150000,1.350000,0.210000,12.500000,28.700000,54.025000,243.750000,26338.620000,33254.375000,6.762500,0.790000,71.000000,2026.000000,12.000000,358.500000
max,13.400000,9.200000,10.800000,6.000000,13.700000,8.200000,6.230000,17.000000,42.100000,79.200000,334.000000,29048.190000,37989.800000,8.730000,1.830000,75.000000,2026.000000,12.000000,365.000000

In [8]:
whether.read_whether_data("whether.xlsx")

,date,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,snowfall_sum,precipitation_hours,wind_speed_10m_max,...,sunrise,sunset,sunshine_duration,daylight_duration,shortwave_radiation_sum,et0_fao_evapotranspiration,weather_code,year,month,day_of_year
0,2026-01-15,4.6,0.4,0.8,-4.8,13.7,4.8,6.23,16,20.9,...,2026-01-15T08:02,2026-01-15T17:14,29.05,33088.98,3.03,0.50,75.0,2026,1,15
1,2026-01-16,-0.3,-3.2,-4.4,-8.1,3.2,0.0,2.24,6,21.4,...,2026-01-16T08:02,2026-01-16T17:15,27756.13,33198.27,7.02,0.63,75.0,2026,1,16
2,2026-01-17,-3.6,-7.9,-8.9,-14.8,2.6,0.0,1.82,12,28.8,...,2026-01-17T08:01,2026-01-17T17:16,13402.40,33310.48,5.92,0.34,73.0,2026,1,17
3,2026-01-18,-3.0,-6.0,-10.2,-13.1,0.0,0.0,0.00,0,32.5,...,2026-01-18T08:01,2026-01-18T17:18,26365.04,33425.46,7.34,0.43,3.0,2026,1,18
4,2026-01-19,-4.3,-7.5,-11.9,-15.6,0.0,0.0,0.00,0,37.6,...,2026-01-19T08:00,2026-01-19T17:19,27739.41,33543.05,7.77,0.38,3.0,2026,1,19
5,2026-01-20,-2.6,-9.9,-7.2,-16.4,0.0,0.0,0.00,0,27.5,...,2026-01-20T07:59,2026-01-20T17:20,28422.13,33663.09,8.73,0.49,3.0,2026,1,20
6,2026-02-15,12.5,7.9,6.9,4.8,0.0,0.0,0.00,0,39.0,...,2026-02-15T07:29,2026-02-15T17:56,20644.93,37637.72,7.46,1.23,3.0,2026,2,46
7,2026-02-16,13.4,9.2,9.4,6.0,1.8,1.8,0.00,3,42.1,...,2026-02-16T07:28,2026-02-16T17:58,29048.19,37813.00,7.24,1.83,61.0,2026,2,47
8,2026-02-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,...,2026-02-17T07:26,2026-02-17T17:59,NaN,37989.80,NaN,NaN,NaN,2026,2,48